<div class="homepage-container">
        <div class="titleText-1">
            <h1>RENTAL EQUIPMENT IS NOW AVAILABLE ONLINE!</h1>
                 <div class="paragraph-text-1">
                     <h2>From scooters, beds, lifts chairs, and more - you can now rent your equipment online.</h2>
                 </div>
                 <div class="button-div">
                     <a href="/rental.html"><button class="button-1"> Rent Now </button></a>
                </div>
         </div>
    <div class="chair-image"><img src="" alt=""></div>
</div>

<div class="information-container">
    <div class="infobox">
        <div class="infobox-img"><a href="/rental.html"><img src="pub/media/wysiwyg/DahlContentPhotos/computer-1.png" alt=""></div></a>
        <h3>Rent Equipment Online</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
    <div class="infobox">
        <div class="infobox-img"><a href="diabetic-shoes"><img src="pub/media/wysiwyg/DahlContentPhotos/steps_icon.png" alt=""></div></a>
        <h3>Diabetic Shoe Information</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
    <div class="infobox">
        <div class="infobox-img"><a href="coverage-insurance"><img src="pub/media/wysiwyg/DahlContentPhotos/healthcareheart.png" alt=""></div></a>
        <h3>Insurance Information</h3>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
</div>



<div class="promise-container">
    <div class="promisebox">
        <h1>The Dahl Medical Promise</h1>
        <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tortor dui, faucibus non pharetra at, consectetur non ex.</h2>
    </div>
</div>



<div class="contact-container">
    <div class="contactbox">
        <div class="contactImage">
            <img src="/pub/media/wysiwyg/529679220.jpg" alt="" >
        </div>
        <h2>Have a question? Give us a call!</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>


    <div class="contactbox">
        <div class="contactImage">
            <img src="/pub/media/wysiwyg/519265074.jpg" alt="">
        </div>
            <h2>Request a catalog.</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <form class="requestCatalog" action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>" method="post">
             <input name="email" type="email" placeholder="Email Address" >
            <div class="actions">
                <button class="action subscribe primary"  type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Get Catalog') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>